### ISSUE TITLE
[FR]Fukungaが参加

### ISSUE THREAD

**Issue by Fukunga** [Fukunga/hunny#1]
アプリ内に新しく Fukunga のデータを追加します

**Comment by rbdog** [comment]
@Fukunga 
こんにちは！　残念っっながら　issue を立てる場所を間違えています😆
ここは、ふくんがさんが フォーク（本家ハニーからコピー）してきたほうの"ふくんが専用ハニープロジェクト"です。
ですのでこの「#1」のissueは不要クローズしてOKです！

本家ハニーのissueはこちらからお願いします。 
[イシューissueを発行](https://github.com/rubydog-jp/hunny/issues)

発行し終わったら、もう一度さいごの手順、「プルリクエストを作る」をやってみてください😁
[プルリクエストを作成](https://github.com/rubydog-jp/hunny/pulls)

お待ちしておりま〜す
